//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class Country
    {
        #region Primitive Properties
    
        public virtual System.Guid id
        {
            get;
            set;
        }
    
        public virtual string code
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Region> Regions
        {
            get
            {
                if (_regions == null)
                {
                    var newCollection = new FixupCollection<Region>();
                    newCollection.CollectionChanged += FixupRegions;
                    _regions = newCollection;
                }
                return _regions;
            }
            set
            {
                if (!ReferenceEquals(_regions, value))
                {
                    var previousValue = _regions as FixupCollection<Region>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRegions;
                    }
                    _regions = value;
                    var newValue = value as FixupCollection<Region>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRegions;
                    }
                }
            }
        }
        private ICollection<Region> _regions;

        #endregion
        #region Association Fixup
    
        private void FixupRegions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Region item in e.NewItems)
                {
                    item.Country = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Region item in e.OldItems)
                {
                    if (ReferenceEquals(item.Country, this))
                    {
                        item.Country = null;
                    }
                }
            }
        }

        #endregion
    }
}
