//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class ExternalAccount
    {
        #region Primitive Properties
    
        public virtual System.Guid id
        {
            get;
            set;
        }
    
        public virtual string accountTye
        {
            get;
            set;
        }
    
        public virtual string username
        {
            get;
            set;
        }
    
        public virtual string passwd
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> verified
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> memberId
        {
            get { return _memberId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_memberId != value)
                    {
                        if (Member != null && Member.id != value)
                        {
                            Member = null;
                        }
                        _memberId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _memberId;

        #endregion
        #region Navigation Properties
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.ExternalAccounts.Contains(this))
            {
                previousValue.ExternalAccounts.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.ExternalAccounts.Contains(this))
                {
                    Member.ExternalAccounts.Add(this);
                }
                if (memberId != Member.id)
                {
                    memberId = Member.id;
                }
            }
            else if (!_settingFK)
            {
                memberId = null;
            }
        }

        #endregion
    }
}
