//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class Medium
    {
        #region Primitive Properties
    
        public virtual System.Guid id
        {
            get;
            set;
        }
    
        public virtual string title
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dateUploaded
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> seedId
        {
            get { return _seedId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_seedId != value)
                    {
                        if (Seed != null && Seed.id != value)
                        {
                            Seed = null;
                        }
                        _seedId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _seedId;
    
        public virtual Nullable<System.Guid> uploadedById
        {
            get { return _uploadedById; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_uploadedById != value)
                    {
                        if (Member != null && Member.id != value)
                        {
                            Member = null;
                        }
                        _uploadedById = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _uploadedById;
    
        public virtual string type
        {
            get;
            set;
        }
    
        public virtual string path
        {
            get;
            set;
        }
    
        public virtual string embedScript
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Seed Seed
        {
            get { return _seed; }
            set
            {
                if (!ReferenceEquals(_seed, value))
                {
                    var previousValue = _seed;
                    _seed = value;
                    FixupSeed(previousValue);
                }
            }
        }
        private Seed _seed;
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupSeed(Seed previousValue)
        {
            if (previousValue != null && previousValue.Media.Contains(this))
            {
                previousValue.Media.Remove(this);
            }
    
            if (Seed != null)
            {
                if (!Seed.Media.Contains(this))
                {
                    Seed.Media.Add(this);
                }
                if (seedId != Seed.id)
                {
                    seedId = Seed.id;
                }
            }
            else if (!_settingFK)
            {
                seedId = null;
            }
        }
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.Media.Contains(this))
            {
                previousValue.Media.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.Media.Contains(this))
                {
                    Member.Media.Add(this);
                }
                if (uploadedById != Member.id)
                {
                    uploadedById = Member.id;
                }
            }
            else if (!_settingFK)
            {
                uploadedById = null;
            }
        }

        #endregion
    }
}
