//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class MemberProfile
    {
        #region Primitive Properties
    
        public virtual System.Guid id
        {
            get;
            set;
        }
    
        public virtual string sex
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dob
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> memberId
        {
            get { return _memberId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_memberId != value)
                    {
                        if (Member != null && Member.id != value)
                        {
                            Member = null;
                        }
                        if (Member1 != null && Member1.id != value)
                        {
                            Member1 = null;
                        }
                        _memberId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _memberId;
    
        public virtual Nullable<System.Guid> locationId
        {
            get { return _locationId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_locationId != value)
                    {
                        if (Location != null && Location.id != value)
                        {
                            Location = null;
                        }
                        if (Location1 != null && Location1.id != value)
                        {
                            Location1 = null;
                        }
                        _locationId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _locationId;
    
        public virtual string imagePath
        {
            get;
            set;
        }
    
        public virtual string setURL
        {
            get;
            set;
        }
    
        public virtual string bio
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Location Location
        {
            get { return _location; }
            set
            {
                if (!ReferenceEquals(_location, value))
                {
                    var previousValue = _location;
                    _location = value;
                    FixupLocation(previousValue);
                }
            }
        }
        private Location _location;
    
        public virtual Location Location1
        {
            get { return _location1; }
            set
            {
                if (!ReferenceEquals(_location1, value))
                {
                    var previousValue = _location1;
                    _location1 = value;
                    FixupLocation1(previousValue);
                }
            }
        }
        private Location _location1;
    
        public virtual Member Member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    FixupMember(previousValue);
                }
            }
        }
        private Member _member;
    
        public virtual Member Member1
        {
            get { return _member1; }
            set
            {
                if (!ReferenceEquals(_member1, value))
                {
                    var previousValue = _member1;
                    _member1 = value;
                    FixupMember1(previousValue);
                }
            }
        }
        private Member _member1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupLocation(Location previousValue)
        {
            if (previousValue != null && previousValue.MemberProfiles.Contains(this))
            {
                previousValue.MemberProfiles.Remove(this);
            }
    
            if (Location != null)
            {
                if (!Location.MemberProfiles.Contains(this))
                {
                    Location.MemberProfiles.Add(this);
                }
                if (locationId != Location.id)
                {
                    locationId = Location.id;
                }
            }
            else if (!_settingFK)
            {
                locationId = null;
            }
        }
    
        private void FixupLocation1(Location previousValue)
        {
            if (previousValue != null && previousValue.MemberProfiles1.Contains(this))
            {
                previousValue.MemberProfiles1.Remove(this);
            }
    
            if (Location1 != null)
            {
                if (!Location1.MemberProfiles1.Contains(this))
                {
                    Location1.MemberProfiles1.Add(this);
                }
                if (locationId != Location1.id)
                {
                    locationId = Location1.id;
                }
            }
            else if (!_settingFK)
            {
                locationId = null;
            }
        }
    
        private void FixupMember(Member previousValue)
        {
            if (previousValue != null && previousValue.MemberProfiles.Contains(this))
            {
                previousValue.MemberProfiles.Remove(this);
            }
    
            if (Member != null)
            {
                if (!Member.MemberProfiles.Contains(this))
                {
                    Member.MemberProfiles.Add(this);
                }
                if (memberId != Member.id)
                {
                    memberId = Member.id;
                }
            }
            else if (!_settingFK)
            {
                memberId = null;
            }
        }
    
        private void FixupMember1(Member previousValue)
        {
            if (previousValue != null && previousValue.MemberProfiles1.Contains(this))
            {
                previousValue.MemberProfiles1.Remove(this);
            }
    
            if (Member1 != null)
            {
                if (!Member1.MemberProfiles1.Contains(this))
                {
                    Member1.MemberProfiles1.Add(this);
                }
                if (memberId != Member1.id)
                {
                    memberId = Member1.id;
                }
            }
            else if (!_settingFK)
            {
                memberId = null;
            }
        }

        #endregion
    }
}
