//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class MemberRole
    {
        #region Primitive Properties
    
        public string username
        {
            get;
            set;
        }
    
        public string rolename
        {
            get;
            set;
        }
    
        public string status
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> created
        {
            get;
            set;
        }

        #endregion
    }
}
