//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SeedSpeak.Model
{
    public partial class TopSeedPlanter
    {
        #region Primitive Properties
    
        public System.Guid id
        {
            get;
            set;
        }
    
        public string MemberName
        {
            get;
            set;
        }
    
        public Nullable<int> SeedCount
        {
            get;
            set;
        }
    
        public string ImagePath
        {
            get;
            set;
        }
    
        public string organisationName
        {
            get;
            set;
        }

        #endregion
    }
}
